export const CHANGE_LIGHT_THEME = "CHANGE_LIGHT_THEME";
export const CHANGE_DARK_THEME = "CHANGE_DARK_THEME";
export const SELECT_OBJECT = "SELECT_OBJECT";
export const OBJECT_SIZE = "OBJECT_SIZE";
export const OBJECT_WIDTH = "OBJECT_WIDTH";
export const OBJECT_BORDER_RADIUS = "OBJECT_BORDER_RADIUS";
export const OBJECT_OPACITY = "OBJECT_OPACITY";
export const SELECTED_COLOR = "SELECTED_COLOR";
